### ISSUE TITLE
Some DSOs not found in search

### ISSUE THREAD

**Issue by lebodano** [artyom-beilis/skyhopper#14] opened 2023-03-18 13:38 UTC
I can see certain DSOs in the CSV file (one example NGC2244) found in https://raw.githubusercontent.com/mattiaverga/OpenNGC/46694d5825efe9c569c5e137c57a7fba634a9144/NGC.csv but AstroHopper does not find them when I search

**Comment by artyom-beilis** [comment] 2023-03-18 19:11
Because I insert only objects that have known magnitude and above certain threshold since inserting all NGC will be too large. In this case NGC2244 is marked as duplicate of 2239 in the OpenNGC and 2239 is present

**Comment by artyom-beilis** [comment] 2023-03-18 19:12
Also probably it may be good idea to put them all even if I don't show all of them at the map.

**Comment by lebodano** [comment] 2023-03-19 01:43
Fair. I'm more novice so the more you can include the better. This app completely changed my viewing experience. I agree showing them on the map would be way too much but at least me being able to input any of them and pull them would be ideal. Thanks for all you do!

**Comment by lebodano** [comment] 2023-03-20 11:29
What about then not only the ability to pull any object in the app by search but also having a toggle where I can check a box to display any messier object or Caldwell object on the map. Since I don't really know what is in the sky, this could help me find more objects than just what is displayed currently and up to the user to determine how cluttered the sky map gets. This is based on me freezing last night literally typing m1, m2, m3.... trying to find objects around me

**Comment by lebodano** [comment] 2023-06-01 19:35
Currently, I try to use this app, cannot find many objects in view, change screens to stellarium (or whatever skymap etc). then come back, I have to recalibrate, and find an object. Rinse and repeat n times. It would be super helpful so have the ability to check a box to display all messier objects or Caldwell objects vs having to know what's in the sky ahead of time if possible :) Anyway, I really appreciate the work you do, this app has helped me from quitting the hobby!

**Comment by artyom-beilis** [comment] 2023-06-01 19:42
You can control how many objects are shown by increasing DSO magnitude.

Also you can always search DSO by name. I also like to organize DOSs in watch list according to preference.

Also I think I need to add a feature of increasing number of DSO shown when you zoom in more.

**Comment by lebodano** [comment] 2023-06-01 20:07
I had no idea, this is amazing, thank you so much!

**Closed** 2023-06-05 07:37 UTC
